# Generated by Django 3.2 on 2022-06-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0007_dislike_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='Post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='Post',
            new_name='post',
        ),
    ]
